<?xml version='1.0'?>

<robot name="myrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:property name="mass" value="5" />

  <xacro:property name="radius" value="0.1" />
  <xacro:property name="length" value="0.05" />

  <xacro:property name="wheel_width" value="0.010" />
  <xacro:property name="box_height" value="0.6" />
  <xacro:property name="box_width" value="0.52" />
  <xacro:property name="box_length" value="0.1" />
  <xacro:property name="euler" value="1.5707" />
  <xacro:property name="friction" value="0" />
  <xacro:property name="damping" value="0" />



  <link name='base_link'>
    <pose>0 0 0.1 0 0 0</pose>

    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0.0 0 0.1" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name='collision'>
      <geometry>
        <box size="${box_height} ${box_width} ${box_length} "/>
      </geometry>
    </collision>

    <visual name='govde_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${box_height} ${box_width} ${box_length} "/>
      </geometry>
      <material name="green"/>
    </visual>

  </link>


  <link name="sol_on_teker">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 ${euler} ${euler}"/>
      <geometry>
        <cylinder radius="${radius}" length="${length}"/>
      </geometry>
    </collision>

    <visual name="sol_on_teker_visual">
      <origin xyz="0 0 0" rpy="0 ${euler} ${euler}"/>
      <geometry>
        <cylinder radius="${radius}" length="${length}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 ${euler} ${euler}"/>
      <mass value="${mass}"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
    </inertial>
  </link>

  <link name="sag_on_teker">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 ${euler} ${euler}"/>
      <geometry>
        <cylinder radius="${radius}" length="${length}"/>
      </geometry>
    </collision>
    <visual name="sag_on_teker_visual">
      <origin xyz="0 0 0" rpy="0 ${euler} ${euler}"/>
      <geometry>
        <cylinder radius="${radius}" length="${length}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 ${euler} ${euler}"/>
      <mass value="${mass}"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
    </inertial>
  </link>

  <link name="sag_arka_teker">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 ${euler} ${euler}"/>
      <geometry>
        <cylinder radius="${radius}" length="${length}"/>
      </geometry>
    </collision>
    <visual name="sag_arka_teker_visual">
      <origin xyz="0 0 0" rpy="0 ${euler} ${euler}"/>
      <geometry>
        <cylinder radius="${radius}" length="${length}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 ${euler} ${euler}"/>
      <mass value="${mass}"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
    </inertial>
  </link>

  <link name="sol_arka_teker">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 ${euler} ${euler}"/>
      <geometry>
        <cylinder radius="${radius}" length="${length}"/>
      </geometry>
    </collision>
    <visual name="sol_arka_teker_visual">
      <origin xyz="0 0 0" rpy="0 ${euler} ${euler}"/>
      <geometry>
        <cylinder radius="${radius}" length="${length}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 ${euler} ${euler}"/>
      <mass value="${mass}"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
    </inertial>
  </link>

  <link name="laser_frame">
    <visual>
        <geometry>
            <cylinder radius="0.05" length="0.04"/>
        </geometry>
        <material name="red"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="0.05" length="0.04"/>
        </geometry>
    </collision>
    <inertial>

      <origin xyz="0 0 0" rpy="0 ${euler} ${euler}"/>
      <mass value="${mass}"/>
      <inertia
        ixx=".1" ixy="0.0" ixz="0.0"
        iyy=".1" iyz="0.0"
        izz=".1"/>
    </inertial>
  </link>
  
  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  <link name="ultrasonic_sensor_link">
    <inertial>
      <mass value="0.001" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia ixx="0.000000017" ixy="0" ixz="0" iyy="0.000000017" iyz="0" izz="0.000000017" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://custom_robot/meshes/max_sonar_ez4.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
    </collision>
  </link>
  
  <joint name="ultrasonic_sensor_joint" type="fixed">
    
    <origin xyz="${length*2 + box_length*2}  0 0 " rpy=" 0 0 0" /> 
      
    <parent link="base_link" />
    <child link="ultrasonic_sensor_link" />
    <axis xyz="0 0 0" />
  </joint>

  

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_frame"/>
    <origin xyz="0.10 0 0.12" rpy="0 0 0"/>
</joint>


  <joint type="continuous" name="sol_on_teker_joint">
    
    <origin xyz="${length*2 + box_length*2}  ${length*2 + box_length*2} 0 " rpy=" 0 0 0" /> 

    <child link="sol_on_teker"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <joint_properties damping="${damping}" friction="${friction}"/>
  </joint>

  <joint type="continuous" name="sol_arka_teker_joint">
    <origin xyz=" -${length*2 + box_length*2}  -${length*2 + box_length*2} 0 " rpy=" 0 0 0" /> 
    <child link="sol_arka_teker"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <joint_properties damping="${damping}" friction="${friction}"/>
  </joint>


  <joint type="continuous" name="sag_on_teker_joint">
    <origin xyz=" -${length*2 + box_length*2}  ${length*2 + box_length*2} 0 " rpy=" 0 0 0" /> 
    <child link="sag_on_teker"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <joint_properties damping="${damping}" friction="${friction}"/>
  </joint>


  <joint type="continuous" name="sag_arka_teker_joint">
    <origin xyz="${length*2 + box_length*2}  -${length*2 + box_length*2} 0 " rpy=" 0 0 0" /> 
    <child link="sag_arka_teker"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <joint_properties damping="${damping}" friction="${friction}"/>
  </joint>


  
  
  <transmission name="tran1">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="sol_on_teker_joint">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor1">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
  </transmission>

  <transmission name="tran2">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="sol_arka_teker_joint">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor2">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>2</mechanicalReduction>
  </actuator>
  </transmission>


   
    
  <transmission name="tran3">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="sag_on_teker_joint">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor3">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>3</mechanicalReduction>
  </actuator>
  </transmission>



  <transmission name="tran4">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="sag_arka_teker_joint">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="motor4">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>4</mechanicalReduction>
  </actuator>
  </transmission>

  <gazebo>
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <updateRate>20.0</updateRate>
      <robotNamespace>/</robotNamespace>
      <leftFrontJoint>sol_on_teker_joint</leftFrontJoint>
      <rightFrontJoint>sag_on_teker_joint</rightFrontJoint>
      <leftRearJoint>sol_arka_teker_joint</leftRearJoint>
      <rightRearJoint>sag_arka_teker_joint</rightRearJoint>
      <wheelSeparation>0.5</wheelSeparation>
      <wheelDiameter>0.2</wheelDiameter>
      <robotBaseFrame>base_link</robotBaseFrame>
      <torque>5</torque>
      <MaxForce>5.0</MaxForce>
      <commandTopic>cmd_vel</commandTopic>
      <broadcastTF>true</broadcastTF>
      <!--<odometryTopic>odom</odometryTopic>
      <odometryFrame>/odom</odometryFrame>-->
      <covariance_x>0.000100</covariance_x>
      <covariance_y>0.000100</covariance_y>
      <covariance_yaw>0.010000</covariance_yaw>
    </plugin>
</gazebo>

  <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/myrobot</robotNamespace>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        </plugin>
  </gazebo>   

  <gazebo reference="ultrasonic_sensor_link">        
    <sensor type="ray" name="TeraRanger">
       <pose>0 0 0 0 0 0</pose>
       <visualize>true</visualize>
       <update_rate>50</update_rate>
       <ray>
          <scan>
             <horizontal>
                <samples>10</samples>
                <resolution>1</resolution> 
                <min_angle>-0.14835</min_angle>
                <max_angle>0.14835</max_angle>
             </horizontal>
             <vertical>
                <samples>10</samples>
                <resolution>1</resolution> 
                <min_angle>-0.04</min_angle>
                <max_angle>0.04</max_angle> 
             </vertical>
          </scan>
          <range>
             <min>0.01</min>
             <max>2</max>
             <resolution>0.02</resolution>
          </range>
       </ray>
       <plugin filename="libgazebo_ros_range.so" name="gazebo_ros_range">
          <gaussianNoise>0.005</gaussianNoise>
          <alwaysOn>true</alwaysOn>
          <updateRate>50</updateRate>
          <topicName>/ir_sensor</topicName>
          <frameName>ultrasonic_sensor_link</frameName>
          <radiation>INFRARED</radiation>
          <fov>0.2967</fov>
       </plugin>
    </sensor>  
    </gazebo>


  <gazebo reference="laser_frame">
    <sensor type="ray" name="head_rplidar_sensor">
      <pose>0 0 0.5 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>100</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-2.0</min_angle>
            <max_angle>2.0</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.2</min>
          <max>12.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_rplidar_controller" filename="libgazebo_ros_laser.so">
        <topicName>scan</topicName>
        <frameName>laser_frame</frameName>
      </plugin>
    </sensor>
  </gazebo>
  


  <material name="yellow" >
    <color rgba="1.0 1.0 0.0784313725490196 1.0" />
  </material>
  <material name="green" >
    <color rgba="0.08235294117647059 0.6901960784313725 0.10196078431372549 1.0" />
  </material>




</robot>